Hide all finished tasks and show all tasks
CS2103AUG2016-T11-C4/main pull request #138
Opened 2016-10-26 16:13 UTC by nightism

Two functions added:
1. Hide all finished deadline/floating tasks from the user interface.
2. Show all deadline/floating tasks after some of them are hidden from the user interface.

2016-10-26 16:13 UTC, nightism commented
@pyokagan sorry for the late pull request

2016-10-26 16:18 UTC, pyokagan requested changes
Avoid adding new methods to the `Model` interface unless absolutely necessary.

2016-10-26 16:18 UTC, pyokagan commented on src/main/java/seedu/address/model/ModelManager.java
> +    }
@nightism Looks like you can just do `setDeadlineTaskFilter(new DeadlineTaskFinishedPredicate())` in `HideFinishedDeadlineCommand`, no?

2016-10-26 16:18 UTC, pyokagan commented on src/main/java/seedu/address/model/ModelManager.java
> +    }
Same goes for all the other methods you added to the `Model` interface just to set a filter.

2016-10-26 16:22 UTC, pyokagan commented on src/main/java/seedu/address/logic/commands/MarkDeadlineFinishedCommand.java
> +            model.setDeadlineTask(targetIndex, finishedDeadlineTask);
@nightism Yeah, sorry about that...

2016-10-26 17:28 UTC, nightism commented on src/main/java/seedu/address/model/ModelManager.java
> +    }
ok

2016-10-26 17:51 UTC, pyokagan requested changes
!!?!??!?!? The code does not even compile.

2016-10-26 17:52 UTC, pyokagan commented on src/main/java/seedu/address/logic/commands/HideFinishedFloatingTaskCommand.java
> +        model.setIsFinishedFloatingTaskFilter();
Remove these kinds of methods and use `model.setFloatingTaskFilter()` instead.

2016-10-27 08:43 UTC, pyokagan commented
Merged as d9ee9057c4cf961860fec3be42a59c0e613663cf

2016-10-27 08:43 UTC, closed without merging