Search Command: Search using keywords
CS2103AUG2016-T11-C4/main pull request #95
Opened 2016-10-19 23:47 UTC by snehasp13

Not sure how to pass Set<String> data type in a method - the commented out part in SearchParserTest class

2016-10-20 01:42 UTC, pyokagan requested changes
The implementation is not correct. Also has Checkstyle errors.

2016-10-20 01:42 UTC, pyokagan commented on src/main/java/seedu/address/logic/commands/SearchCommand.java
> +	 public static final String COMMAND_WORD = "Search";
Why does it start with a capital letter?

2016-10-20 01:42 UTC, pyokagan commented on src/test/java/seedu/address/logic/parser/SearchParserTest.java
> +			assertParse("searchWord", "searchWord"); //Find how to pass a Set<String> in a method
`Set` is an interface. You are probably looking for an implementation of that interface, such as `HashSet`?

2016-10-20 01:42 UTC, pyokagan commented on src/main/java/seedu/address/logic/parser/SearchParser.java
> +    	final Matcher matcher = CMD_PATTERN.matcher(args.trim());
Seems like this would not properly split the string? Probably should involve a `String.split()`?

2016-10-20 01:42 UTC, pyokagan commented on src/main/java/seedu/address/logic/parser/SearchParser.java
> +            Pattern.compile("^(?<keyword>)"+"$");
This regular expression only matches the empty string...

2016-10-25 16:08 UTC, pyokagan commented
@snehasp13 What's the status of this PR?

2016-10-26 01:49 UTC, snehasp13 commented
The code is done, but I'm not able to run it as a java application and test it due to some compilation error in CommandBoxTest.java and JsonConfigStorag.java....I didn't change or write anything in these 2 classes, so don't know how to solve it

2016-10-26 06:26 UTC, pyokagan commented
Why not post the code then?

2016-11-02 16:07 UTC, closed without merging